# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

base_domain: lvh.me
asset_host: "http://lvh.me:5000"

development:
  secret_key_base: 8467e707c4a6fbd8fdeac5cc1b0eef17d6a3917f62e5cf38b9646c5b2f727d37a9c05722591aaf285b12319d7d295769db8e5ffac322fa18a837dc4ed5c264b2

test:
  secret_key_base: f0804ac0d2e39f67e73520842cb27aba0dfc9de145d034c22f71aa3c15cb25c59a2869447b6a0bf3990e2c388769c25adb54b6a0969500b5a61f0499ab535fb5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
